<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
    <OpenApiDocumentsDirectory>$(MSBuildThisFileDirectory)..\..\..\contracts\openapi</OpenApiDocumentsDirectory>
    <OpenApiGenerateDocumentsOptions>--file-name workboard-v1</OpenApiGenerateDocumentsOptions>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Workboard.Application\Workboard.Application.csproj" />
    <ProjectReference Include="..\Workboard.Infrastructure\Workboard.Infrastructure.csproj" />
  </ItemGroup>

</Project>

